[package]
name = "ckbez"
version = "0.119.0"
edition = "2021"
description = "CKB Easy is an experimental project that aims to provide human-friendly interfaces for common CKB operations."
license = "MIT"

[dependencies]
ckb-chain-spec = "0.119"
ckb-error = "0.119"
ckb-hash = "0.119"
ckb-script = "0.119"
ckb-traits = "0.119"
ckb-types = "0.119"
hex = "0.4"
